In [1]:
z = 1 + 3J

In [2]:
z.imag

3.0

In [3]:
z.conjugate()

(1-3j)

In [152]:
from math import sqrt, atan2
import numbers

class Complex(object):
    def __init__(self, real_part, imaginary_part):
        self.re = real_part
        self.im = imaginary_part

    def norm(self):
        return sqrt(self.re**2 + self.im**2)
    
    def conjugate(self):
        return Complex(self.re, -self.im)
    
    def multiply_by_a_number(self, x):
        return Complex(x*self.re, x*self.im)
    
    def __mul__(self, other):
        if isinstance(other, numbers.Number):
            return self.multiply_by_a_number(other)
        if isinstance(other, Complex):
            return Complex(self.re*other.re - self.im*other.im,
                          self.re*other.im + self.im*other.re)
        return NotImplemented
        
    def __rmul__(self, other):
        return self*other
        
    def __repr__(self):
        return "Complex({}, {})".format(self.re, self.im)
    
    def __str__(self):
        if self.im>0:
            return '{} + {}i'.format(self.re, self.im)
        else:
            return '{} - {}i'.format(self.re, -self.im)
        
    def __getitem__(self, index):
        if index==0:
            return self.re
        if index==1:
            return self.im
        raise Exception('Index shoud be 0 or 1')
        
    def __eq__(self, other):
        if isinstance(other, Complex):
            return (self.re==other.re) and (self.im==other.im)
        return False
    
    @property
    def r(self):
        return self.norm()
    
    @property
    def theta(self):
        return atan2(self.im, self.re)
    
class PureImaginary(Complex):
    def __init__(self, imaginary_part):
        Complex.__init__(self, 0, imaginary_part)
        
    def __repr__(self):
        return 'PureImaginary({})'.format(self.im)

In [154]:
z = Complex(1, 3)
z2 = PureImaginary(3)
z2*z

Complex(-9, 3)

In [131]:
z1 = Complex(1, 3)
z2 = Complex(1, 3)
z3 = z1

z1==z2

True

In [124]:
z = Complex(1, 3)
z[1]

3

In [119]:
z = Complex(1, 3)
#z.multiply_by_a_number(3.1415)
print(z*3.1415)
print(z*z.conjugate())
3.1415*z

3.1415 + 9.4245i
10 - 0i


Complex(3.1415, 9.4245)

In [90]:
z = Complex(1, 3)
print(z.re)
print(z.norm())

1
3.1622776601683795


In [91]:
z.conjugate()

Complex(1, -3)

In [88]:
print(z)
print(z.conjugate())

1 + 3i
1 - 3i


In [50]:
isinstance(z, Complex)

True

In [51]:
z.re = 1.2
z.im = 3
z.norm()

3.2310988842807022

In [18]:
#z.a_stupid_attribute = "Hello"

In [44]:
#z.a = "Bonjour"

In [45]:
z.__dict__

{'re': 1.2, 'im': 3, 'a': 'Bonjour'}

In [46]:
z2 = Complex()

In [47]:
#z2.a

'Hello'

In [64]:
z2

In [79]:
s = "Hello"
print(s)

Hello


In [100]:
str(z)

'1 + 3i'

In [101]:
repr(z)

'Complex(1, 3)'

In [111]:
import numpy as np
from numpy import array
a = np.random.rand(3, 3)

In [112]:
str(a)

'[[0.59249553 0.19985384 0.5164116 ]\n [0.01377854 0.05958016 0.99287052]\n [0.81275244 0.53460939 0.62396789]]'

In [113]:
print(repr(a))

array([[0.59249553, 0.19985384, 0.5164116 ],
       [0.01377854, 0.05958016, 0.99287052],
       [0.81275244, 0.53460939, 0.62396789]])


In [114]:
array([[0.32921364, 0.10298433, 0.83120605],
       [0.84227139, 0.30174352, 0.6019039 ],
       [0.01512626, 0.05772147, 0.88824969]])

array([[0.32921364, 0.10298433, 0.83120605],
       [0.84227139, 0.30174352, 0.6019039 ],
       [0.01512626, 0.05772147, 0.88824969]])

In [132]:
def multiplication(a, b):
    out = a.__mul__(b)
    if out!=NotImplemented:
        return out
    out = b.__rmul__(a)
    if out!=NotImplemented:
        return out
    raise Exception('Cannot multipliy {} by {}'.format(type(a), type(b))
                   )
    

In [137]:
multiplication(z, z.conjugate())

Complex(10, 0)

In [156]:
Complex.norm

<function __main__.Complex.norm(self)>